# Generated by Django 2.0.9 on 2018-11-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pushlished_date',
            new_name='published_date',
        ),
    ]
